### ISSUE TITLE
Could not detect the problem when making a new plugin

### ISSUE THREAD

**Issue by kukrik** [qcubed/application#16]
I am trying to develop a new plugin called NestedSortable, but I could not identify one problem. The thing is that I use the extension \QCubed\Project\Jqui\Sortable when constructing NestedSortable. Development is still underway and I can not debug  step by step if that one problem is ahead. I made a screenshot where the yellow box comes from the Sortable class and should not be there.

<img width="1222" alt="screen shot 2018-03-02 at 11 33 41" src="https://user-images.githubusercontent.com/2853034/36925488-d7e94cd2-1e7b-11e8-8a72-685fb60ff6b3.png">

In the NestedSortable class, I wrote the following code that should exclude this yellow box:

```php
public function getEndScript()
    {
        $strJS = parent::getEndScript();

        $strCtrlJs = <<<FUNC
			;\$j('#{$this->ControlId}').on("sortstop", function (event, ui) {
						var ary = jQuery(this).nestedSortable("serialize");
						var str = ary.join(",");
			 			qcubed.recordControlModification("$this->ControlId", "_ItemArray", str);
					})
FUNC;
        Application::executeJavaScript($strCtrlJs, Application::PRIORITY_HIGH);

        return $strJS;
    }

```

I know that work is underway, but now it's not possible to debug this problem. I could not figure out where to look for this mistake.

Please advise on how to proceed. Thank you!

PS. I thought in the meantime that a similar problem could be in the QCubed v4 core? I've noticed that, for example, QCubed v3 and QCubed v4 plugins for the PhoneTextBox are exactly the same. But QCubed v4 throws it at the double: 

<img width="503" alt="33790055-ae0ca5c2-dc85-11e7-9b39-486a5c63db1f" src="https://user-images.githubusercontent.com/2853034/36926121-bea7ae64-1e7e-11e8-8637-93cf54fae49a.png">

Perhaps this problem can cause this? What do you think of it?

**Comment by kukrik** [comment]
@spekary, did you see my question? This problem should find a solution. Please give at least know that you examine it. Thank you!

**Comment by spekary** [comment]
This is a basic PHP thing. If you do not want the default behavior of the parent, then do not call the parent function.

```$strJS = parent::getEndScript()```

instead, replace that with:

```$strJS = QCubed\Control\Panel::getEndScript()```

to bypass the parent.

The phonetextbox problem is a different problem.

**Comment by kukrik** [comment]
@spekary, many thanks! I got even smarter, it can move forward...

That or the second line is working correctly:
`$strJS = Q\Control\BlockControl::getEndScript();`
`$strJS = Q\Control\Panel::getEndScript();`

I have a couple more issues, but I'm not asking questions right away. I will examine it again thoroughly. If I can not cope, then I ask specific questions.

Thank you once again!
