### ISSUE TITLE
I've used QCubed 1.1 for a long time, modified and extended it a lot (incl. code generator)...

### ISSUE THREAD

**Issue by alexsee75** [qcubed/application#22]
... now it's probably time to update! (I have about a dozen applications, and one of them currently gets a major face lift. ;-)

Should I update to V4 or V3(stable)? Where is the current development focus? Is this the right repo for V4 or is there a newer one?

What is the status of V3/V4 concerning PHP 7.3/7.4 compatibility and production use?
(i.e. how much work still to be done to have basically the same functionality as QCubed 1.1 ;-)
I'd be happy to contribute in the development and bugfixes insofar it is something that I need myself...
since it probably does not make lots of sense to port my old QCubed 1.1. modifications....

Best,
  Alex

**Comment by kukrik** [comment]
I've never heard of you before, so you're always welcome! 

Rather, you still need to focus on QCubed v4. I have been using and developing this version for a long time. I don't have a problem with PHP 7.4.7 and MySQL 8.0.19 with this version. In development, I aim for the latest versions to be sure that v4 will work for a long time in the future, and so on...

I have to admit that the community is very passive, but I keep defying ... I just like it.

Even in this version of v4, the main ideologue @spekary recommended to start using the GO language QCubed. This is an interesting challenge. But I have to finish some projects. Then I start researching and so on...

And sometimes another developer @matthiaz interacts.

In any case, I recommend taking QCubed v4. I am always helpful as far as I can answer.

**Comment by matthiaz** [comment]
I'm around. Although I must admit, I haven't spent much time on github in the past year. Life got in the way.

I can recommend QCubed V4 for any new project (unless you want to switch to something like Laravel)
Last project I launched was with V4, and while it does take a bit to set up, it will be easier to maintain. I also welcome any Pull Requests. 

Having said that, be aware that jumping from qcubed 1 to v4 will be a challenge. It will be like you a rewriting most of your application. 
I too have a QCubed V1.1 project and chose NOT to upgrade. I simply backport all changes that I needed, when I needed it, or wrote my own qcontrol. There is no shame in not being on the latest version. If it works, it works. 

We are in the business of writing software to solve customer problems. We shouldn't always chase the 'this is new and shiny' fad. Use what works for you.

**Comment by spekary** [comment]
As mentioned, my focus is on the goradd project, which is a port of QCubed to GO. 

v4 is here, but its in a branch and not on the master. It works well though, but its pretty stale. No work has been done since version 7.1 of PHP, so there may be some incompatibilities. I don't know.

If you are trying to upgrade a project, I recommend starting over. Install v4, go through the setup steps, make sure the examples work, and then move your database over. Code generate, and pull your code in from the old project.

**Comment by kukrik** [comment]
I have v4 running well on PHP 7.4.7. Of course, in some places these `assert()` need to be corrected a bit, these quotation marks need to be removed. And all...

As for v4 running slowly. So far I haven't seen it, maybe my database isn't too big. Maybe DataGrid can run slowly due to the large amount of data. If you use pagination, it's totally ok for me.

**Comment by alexsee75** [comment]
I've checked out the generated code from V4 and although similar, it is still different enough to make porting an existing code quite complex. So for my current project, which basically merges three old QCubed 1.1 projects into one application, I'll stick with 1.1. But for a new project, I'll consider V4.

Concerning Laravel... I've seen its code and extended apps done by other people, however its syntax is IMHO much too complex. Just extending a query with a new condition took me three tries to get right, mostly because of Lambda syntax. So it's not an option for me. YMMV.

Best & Thanks for the tips, Alex

**Comment by matthiaz** [comment]
For what it's worth: I'm not a big fan of Laravel either :D

**Comment by kukrik** [comment]
I can also say about the OctoberCms based on Laravel. Too complicated and inconvenient for me too. I did 2 small projects and don't want to do more.

**Comment by alexsee75** [comment]
Hi Matthias,

Have you perhaps updated the JS code of QCubed 1.1. to be compatible
with a newer version of jQuery than (I think) 1.5.3?

(Not sure this will work, these emails are kind of strange...)

Best,
  Alex
--
Dr. Alexander K. Seewald

Seewald Solutions
www.seewald.at
Tel. +43 7243 21520
Mob. +43 664 1106886

**Comment by matthiaz** [comment]
Yep, I definitely updated jquery. But I can't remember if I had to make any
changes to make qcubed compatible. Qcubed doesn't exactly use a lot of
advanced jquery features. And most of what was possible in older jquery
version, is possible in newer versions

**Comment by alexsee75** [comment]
Ok, so we are going to update to latest v1.x and see if everything
still works. If we are feeling lucky we'll then try the v3.x upgrade... ;-)

I did some small changes in the QCubed JS code, mainly excluding
some kinds of controlIds from sending data via AJAX and adding a
selective update for Datagrids (mainly so that only changed table
cells need to be transferred instead of all of them), so we'll
probably stick with our slightly modified JS code.

**Comment by kukrik** [comment]
This is a closed ticket, but I still want to report that jQuery version 3.5.1 works well on QCubed v4. At least for me!

**Comment by alexsee75** [comment]
Hi Matthias,

Did you run the old qcubed version on PHP 7? I found that most
things work after little tweaking however I need to require all
files separately since the autoloader no longer works.

If yes, did you write a new autoloader or did you tweak this issue
in the code generation? (e.g. by defining the classes differently)
I would go for the autoloader actually but do not want to reinvent
the wheel. Mostly I'm interested in the speedup between PHP 5.6 and
PHP 7 ;-)

Best,
  Alex
--
Dr. Alexander K. Seewald

Seewald Solutions GmbH
www.seewald.at
Tel. +43 7243 21520
Mob. +43 664 1106886

**Comment by kukrik** [comment]
Hello!

I think it is no longer maintained here, I made my own branch and called it QCubed-4. Then I could maintain and upgrade. I also upgraded Composer to version 2 so everything works as expected. The thing to remember here is that it works up to PHP 8.0.

I'm planning to upgrade QCubed-4 to work with PHP 8.1 and higher. I have to finish one of my big projects first.

This version can be downloaded to a computer with the composer command: composer create-project --stability=dev qcubed-4/app-starter your_dir_name.

Please familiarize yourself with the following:
1) https://github.com/qcubed-4
2) https://github.com/qcubed-4/app-starter

P.S. I didn't need to change or improve the autoloader.
